const numButtons = document.querySelectorAll('.button')
const clearButton = document.querySelector('#clear')
const outputButton = document.querySelector('#output')
const multiplyButton = document.querySelector('#multiply')
const subtractButton = document.querySelector('#subtract')
const decimalButton = document.querySelector('#decimal')
const equalsButton = document.querySelector('#equals')
const addButton = document.querySelector('#add')
